apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
    - name: controller
      port: 9093
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-svc
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: init-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              # Extract pod ordinal (kafka-0 -> 0)
              ORDINAL=${HOSTNAME##*-}
              NODE_ID=$((ORDINAL + 1))
              # External port: 9094 for kafka-0, 9095 for kafka-1, 9096 for kafka-2
              EXTERNAL_PORT=$((9094 + ORDINAL))
              
              echo "KAFKA_NODE_ID=${NODE_ID}" > /config/node.env
              # Listeners:
              # - INTERNAL: For inter-broker comms (DNS based) -> 9092
              # - CONTROLLER: For KRaft voting -> 9093
              # - EXTERNAL: For local access via port-forward (localhost based) -> 9094 container port, advertised as localhost:909X
              echo "KAFKA_ADVERTISED_LISTENERS=INTERNAL://${HOSTNAME}.kafka-svc:9092,CONTROLLER://${HOSTNAME}.kafka-svc:9093,EXTERNAL://localhost:${EXTERNAL_PORT}" >> /config/node.env
              echo "Configured node ${NODE_ID} with external port ${EXTERNAL_PORT}"
          volumeMounts:
            - name: config-env
              mountPath: /config
      containers:
        - name: kafka
          image: apache/kafka:4.0.0
          command:
            - sh
            - -c
            - |
              . /config-env/node.env
              export KAFKA_NODE_ID
              export KAFKA_ADVERTISED_LISTENERS
              /etc/kafka/docker/run
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 9093
              name: controller
            - containerPort: 9094
              name: external
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-svc:9093,2@kafka-1.kafka-svc:9093,3@kafka-2.kafka-svc:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
          volumeMounts:
            - name: config-env
              mountPath: /config-env
            - name: kafka-config
              mountPath: /opt/kafka/config
            - name: kafka-data
              mountPath: /tmp/kafka-logs
            - name: kafka-logs
              mountPath: /opt/kafka/logs
            - name: tmp-dir
              mountPath: /tmp
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: config-env
          emptyDir: {}
        - name: kafka-config
          emptyDir: {}
        - name: kafka-data
          emptyDir: {}
        - name: kafka-logs
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "sandbox-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-0.kafka-svc:9092,kafka-1.kafka-svc:9092,kafka-2.kafka-svc:9092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
spec:
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-ui
spec:
  to:
    kind: Service
    name: kafka-ui-svc
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect